export const products = [
  {
    id: 8,
    title: '25W, 35w, 45w, 65w Univarsal Travel Adapter ',
    slug: 'universal-travel-adapter',
    model: 'Black',
    price: 1290.0,
    originalPrice: 1550.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/adapter/all.png',
    description:
      '২০W/২৫W, ৩৫W, ৪৫W, ৬৫W ওয়াট ইউনিভার্সাল ট্রাভেল অ্যাডাপ্টর যেটি আপনার যেকোনো ডিভাইস চার্জিং এর জন্য পারফেক্ট সলিউশন।',
    images: [
      '/assets/product/adapter/25w-main.png',
      '/assets/product/adapter/35w-main.png',
      '/assets/product/adapter/45w-main.png',
      '/assets/product/adapter/65w-main.png',
    ],
    variants: [
      { type: '25W' },
      { type: '35W' },
      { type: '45W' },
      { type: '65W' },
    ],
  },
  {
    id: 2,
    title: '25W Univarsal Travel Adapter ',
    slug: 'universal-travel-adapter',
    model: 'Black',
    price: 1290.0,
    originalPrice: 1550.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/adapter/25w.jpg',
    description:
      '২৫ ওয়াট ইউনিভার্সাল ট্রাভেল অ্যাডাপ্টর যেটি আপনার যেকোনো ডিভাইস চার্জিং এর জন্য পারফেক্ট সলিউশন।',
    images: [
      '/assets/product/adapter/25w.jpg',
      '/assets/product/adapter/35w.png',
      '/assets/product/adapter/45w.jpg',
      '/assets/product/adapter/65w.jpg',
    ],
    variants: [{ type: '25W' }],
  },
  {
    id: 4,
    title: '35W Univarsal Travel Adapter ',
    slug: 'universal-travel-adapter',
    model: 'Black',
    price: 1550.0,
    originalPrice: 1850.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/adapter/35w.png',
    description:
      '৩৫ ওয়াট ইউনিভার্সাল ট্রাভেল অ্যাডাপ্টর যেটি আপনার যেকোনো ডিভাইস চার্জিং এর জন্য পারফেক্ট সলিউশন।',
    images: [
      '/assets/product/adapter/25w.jpg',
      '/assets/product/adapter/35w.png',
      '/assets/product/adapter/45w.jpg',
      '/assets/product/adapter/65w.jpg',
    ],
    variants: [{ type: '35W' }],
  },
  {
    id: 5,
    title: '45W Univarsal Travel Adapter ',
    slug: 'universal-travel-adapter',
    model: 'Black',
    price: 1650.0,
    originalPrice: 2050.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/adapter/45w.jpg',
    description:
      '৩৫ ওয়াট ইউনিভার্সাল ট্রাভেল অ্যাডাপ্টর যেটি আপনার যেকোনো ডিভাইস চার্জিং এর জন্য পারফেক্ট সলিউশন।',
    images: [
      '/assets/product/adapter/25w.jpg',
      '/assets/product/adapter/35w.png',
      '/assets/product/adapter/45w.jpg',
      '/assets/product/adapter/65w.jpg',
    ],
    variants: [{ type: '45W' }],
  },
  {
    id: 6,
    title: '65W Univarsal Travel Adapter ',
    slug: 'universal-travel-adapter',
    model: 'Black',
    price: 2299.0,
    originalPrice: 2900.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/adapter/65w.jpg',
    description:
      '৩৫ ওয়াট ইউনিভার্সাল ট্রাভেল অ্যাডাপ্টর যেটি আপনার যেকোনো ডিভাইস চার্জিং এর জন্য পারফেক্ট সলিউশন।',
    images: [
      '/assets/product/adapter/25w.jpg',
      '/assets/product/adapter/35w.png',
      '/assets/product/adapter/45w.jpg',
      '/assets/product/adapter/65w.jpg',
    ],
    variants: [{ type: '65W' }],
  },
  {
    id: 1,
    title: 'Adjustable Polarized Sunglass',
    slug: 'adjustable-tint-polarized-sunglass',
    model: 'Black',
    price: 1350.0,
    originalPrice: 2000.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/glass/sunglass_main.jpg',
    description:
      '১-৯ বিভিন্ন লেভেলে আপনার সুবিধা অনুযায়ী এডজাস্ট করুন। স্টাইলিশ সানগ্লাসটি আপনাকে দিবে চোখের প্রশান্তি।',
    images: [
      '/assets/product/glass/sunglass_main.jpg',
      '/assets/product/glass/sunglass5.jpg',
      '/assets/product/glass/sunglass6.jpg',
      '/assets/product/glass/sunglass4.jpg',
    ],
    variants: [{ color: 'Black' }, { color: 'Silver' }, { color: 'Wheat' }],
  },
  // {
  //   id: 1,
  //   title: 'GT4 Pro Smart Watch - Big Screen BT Call',
  //   slug: 'gt4-pro-smart-watch',
  //   model: 'GT4 PRO',
  //   price: 2750.0,
  //   originalPrice: 3200.0,
  //   sectionType: 'hot',
  //   inStock: true,
  //   thumbnail: '/assets/product/watch/watch1.jpg',
  //   description:
  //     'GT4 PRO Smart Watch Big Screen BT Call gt4pro Outdoor Waterproof Sports Fitness Motion Monitoring Men Smartwatch',
  //   images: [
  //     '/assets/product/watch/watch1.jpg',
  //     '/assets/product/watch/watch2.jpg',
  //     '/assets/product/watch/watch4.jpg',
  //     '/assets/product/watch/watch3.jpg',
  //   ],
  //   variants: [{ color: 'Black' }],
  // },
  {
    id: 3,
    title: 'JF132-Portable High-speed Cooling Fan',
    slug: 'portable-high-speed-cooling-fan',
    model: 'JF132',
    price: 1599.0,
    originalPrice: 1750.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/fan/fan-black.avif',
    description:
      'JF132 Portable High-speed Cooling Fan with 0-200 Speed Settings, USB Rechargeable, and Adjustable Tilt for Personal Use',
    images: [
      '/assets/product/fan/fan-pink-bg.png',
      '/assets/product/fan/fan-white-bg.png',
      '/assets/product/fan/fan-blue.png',
      '/assets/product/fan/ice.png',
    ],
    variants: [
      // { color: 'Black' },
      // { color: 'White' },
      // { color: 'Gray' },
      { color: 'mistyrose' },
      // { color: 'cornflowerblue' },
      // { color: 'Beige' },
    ],
  },
  // {
  //   id: 7,
  //   title: 'Borofone iOS Anti Lost Tracker',
  //   slug: 'borofone-anti-lost-tracker',
  //   model: 'BC101',
  //   price: 990.0,
  //   originalPrice: 1350.0,
  //   sectionType: 'hot',
  //   inStock: true,
  //   thumbnail: '/assets/product/tracker/main2.webp',
  //   description:
  //     'Borofone BC101 Smart Finder হলো একটি স্মার্ট ও আধুনিক সলিউশন যা আপনার মূল্যবান জিনিসপত্র হারিয়ে যাওয়া থেকে রক্ষা করবে।',
  //   images: [
  //     '/assets/product/tracker/tracker2.jpg',
  //     '/assets/product/tracker/tracker1.jpg',
  //     '/assets/product/tracker/main2.webp',
  //     '/assets/product/tracker/main.webp',
  //   ], // 💡 UPDATED VARIANTS TO USE 'TYPE' INSTEAD OF 'COLOR'
  //   variants: [{ type: 'Android' }, { type: 'iOS' }],
  // },
  {
    id: 4,
    title: 'Hoco/Borofone Android/iOS Anti Lost Tracker',
    slug: 'anti-lost-tracker',
    model: 'E96A/BC101',
    price: 990.0,
    originalPrice: 1350.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/tracker/main.webp',
    description:
      'Hoco E96A Smart Finder হলো একটি স্মার্ট ও আধুনিক সলিউশন যা আপনার মূল্যবান জিনিসপত্র হারিয়ে যাওয়া থেকে রক্ষা করবে।',
    images: [
      '/assets/product/tracker/tracker1.webp',
      '/assets/product/tracker/tracker1.jpg',
      '/assets/product/tracker/main2.webp',
      '/assets/product/tracker/main.webp',
    ], // 💡 UPDATED VARIANTS TO USE 'TYPE' INSTEAD OF 'COLOR'
    variants: [{ type: 'Android' }, { type: 'iOS' }],
  },
  // {
  //   id: 2,
  //   title: 'Da Smart Ring Model A',
  //   slug: 'da-smart-ring-model-a',
  //   model: 'Model A',
  //   price: 1500.0,
  //   originalPrice: 1800.0,
  //   sectionType: 'normal',
  //   inStock: false,
  //   thumbnail: '/assets/product/ring/ring1.jpeg',
  //   description:
  //     'A sleek and durable artificial leather jacket, ideal for a bold, modern look.',
  //   images: [
  //     '/assets/product/ring/ring1_main.jpeg',
  //     '/assets/product/ring/ring1_side1.jpeg',
  //     '/assets/product/ring/ring1_side2.jpeg',
  //     '/assets/product/ring/ring1_side3.jpeg',
  //   ],
  //   variants: [{ color: 'Black' }, { color: 'White' }, { color: 'Red' }],
  // },
];

export default products;
