export const products = [
  {
    id: 1,
    title: 'GT4 Pro Smart Watch - Big Screen BT Call',
    slug: 'gt4-pro-smart-watch',
    model: 'GT4 PRO',
    price: 2600.0,
    originalPrice: 3200.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/watch/watch1.jpg',
    description:
      'GT4 PRO Smart Watch Big Screen BT Call gt4pro Outdoor Waterproof Sports Fitness Motion Monitoring Men Smartwatch',
    images: [
      '/assets/product/watch/watch1.jpg',
      '/assets/product/watch/watch2.jpg',
      '/assets/product/watch/watch4.jpg',
      '/assets/product/watch/watch3.jpg',
    ],
    variants: [{ color: 'Black' }],
  },
  {
    id: 3,
    title: 'JF132-Portable High-speed Cooling Fan',
    slug: 'portable-high-speed-cooling-fan',
    model: 'JF132',
    price: 1599.0,
    originalPrice: 1750.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/fan/fan-black.avif',
    description:
      'JF132 Portable High-speed Cooling Fan with 0-200 Speed Settings, USB Rechargeable, and Adjustable Tilt for Personal Use',
    images: [
      '/assets/product/fan/fan-front-back.avif',
      '/assets/product/fan/fan-white.avif',
      '/assets/product/fan/fan-pink.avif',
      '/assets/product/fan/fan-black.avif',
    ],
    variants: [
      { color: 'Black' },
      { color: 'White' },
      { color: 'Gray' },
      { color: 'Pink' },
      { color: 'cornflowerblue' },
      { color: 'Beige' },
    ],
  },
  {
    id: 4,
    title: 'Borofone BC101 Anti Lost Tracker',
    slug: 'borofone-anti-lost-tracker',
    model: 'BC101',
    price: 1150.0,
    originalPrice: 1400.0,
    sectionType: 'hot',
    inStock: true,
    thumbnail: '/assets/product/tracker/tracker1.jpg',
    description:
      'Never lose your essentials with the Borofone BC101 Anti-Lost Tracker. This compact 7g device integrates with Apple’s Find My network for real-time location tracking.',
    images: [
      '/assets/product/tracker/tracker1.jpg',
      '/assets/product/tracker/tracker2.jpg',
      '/assets/product/tracker/tracker3.jpg',
      '/assets/product/tracker/tracker4.jpg',
    ],
    variants: [{ color: 'Black' }, { color: 'White' }],
  },
  {
    id: 2,
    title: 'Da Smart Ring Model A',
    slug: 'da-smart-ring-model-a',
    model: 'Model A',
    price: 1500.0,
    originalPrice: 1800.0,
    sectionType: 'normal',
    inStock: false,
    thumbnail: '/assets/product/ring/ring1.jpeg',
    description:
      'A sleek and durable artificial leather jacket, ideal for a bold, modern look.',
    images: [
      '/assets/product/ring/ring1_main.jpeg',
      '/assets/product/ring/ring1_side1.jpeg',
      '/assets/product/ring/ring1_side2.jpeg',
      '/assets/product/ring/ring1_side3.jpeg',
    ],
    variants: [{ color: 'Black' }, { color: 'White' }, { color: 'Red' }],
  },
];

export default products;
